### ISSUE TITLE
oi.Program.run() and argument parsing

### ISSUE THREAD

**Issue by arcimboldo** [walkr/oi#5]
I want to include `oi` to enable IPC to a daemon I am writing.

Unfortunately, it seems that oi.Program class is parsing the command line, but since my program uses cli.app parser to include some option that the internal parser of oi.Program does not recognize, it fails when oi.Program.run() is called (and some options oi.Program doesn't recognize are passed)

This code, for instance, will fail if you run it with option `--foo`:

```
#!/usr/bin/env python

import cli
import cli.app
import logging
import oi
import os
import threading
import time

class Daemon(cli.app.CommandLineApp):

    def setup(self):
        super(Daemon, self).setup()
        self.add_param('--foo', action='store_true')

    def main(self):
        wdir = os.getcwd()

        def commthread():
            try:
                comm = oi.Program(
                    "daemon",
                    "ipc://%s/daemon.sock" % wdir)
                comm.add_command("ping", lambda: "pong")
                comm.run()
            except Exception as ex:
                print("Error while running oi: %s" % ex)

        self.comm = threading.Thread(target=commthread)
        self.comm.start()
        # main loop
        self.main_loop()

    def main_loop(self):
        self.log.info("Entering main loop")
        it = 0
        while True:
            it += 1
            time.sleep(1)

if __name__ == "__main__":
    Daemon().run()
```

The program will hang and print the following error:

```
usage: daemon_buggy.py [-h] [--version] [--debug] [--config [CONFIG]]
daemon_buggy.py: error: unrecognized arguments: --foo
```

I have found a workaround: just passing an `args` class to `oi.Program.run()` with the following attributes will avoid the problem:
- `debug`
- `version`
- `config`

but it's not a clean solution. Do you have any alternative to fix this issue?

**Comment by walkr** [comment]
Augment the program parser directly. Look up the `argparse` to get more information on the types of arguments available.

``` python
comm = oi.Program(...)
comm.parser.add_argument( '--foo', help='set the foo flag', nargs='?')
comm.run()
```

 Or subclass the `oi.Program` and overwrite the `run` method to ignore the arguments you don't care about.

**Comment by arcimboldo** [comment]
I cannot move the command line parsing to the Program, I am subclassing a class which is already doing some argument parsing, and is part of a not-so-small framework (https://github.com/uzh/gc3pie).

So far I've overwritten the run method, but I either create a fake argument list to pass to the oi.Program.run() or I have to copy from oi.Program.run the only code which seems to be important to the module:

```
        # Start workers then wait until they finish work
        [w.start() for w in self.workers]
        [w.join() for w in self.workers]
```

Both solution are suboptimal, and I think you should definitively include also a class that implements the server communication part and yet can be easily included in any generic software.

**Comment by walkr** [comment]
Take a look at [nanoservice](https://github.com/walkr/nanoservice) for the client/server communication part.

Cheers!
